### ISSUE TITLE
Project "Samples"

### ISSUE THREAD

**Issue by nguye117** [AislynLaurent/vesicle-viewer#15]
As it stands currently, in a single project, you can only fit one sample (and its various SAXS and SANS contrasts). You cannot fit files on a single sample by sample basis. To elaborate, in a research project you will have multiple samples you will have to fit (think multiple concentrations of some perturbant). As of now, you have to create multiple project folders to do this. This can get out of hand really quickly with how many projects you'll have if you use this tool on a regular basis.

Suggestion: When you go to generate new parameters, you can select the data files you want to generate the parameters for and thus in the end will fit. This way, you can have many samples of a single project at once, reducing the total projects and clutter you'll have in the end.

**Comment by AislynLaurent** [comment]
Added. Required a database reset to fix dependences.
