### ISSUE TITLE
registration error 

### ISSUE THREAD

**Issue by judithhouston** [AislynLaurent/vesicle-viewer#150]
Hi, I am trying to create an account, but am receiving a server error? Any ideas? Thanks and best wishes
Judith

**Comment by AislynLaurent** [comment]
Can you describe the error in more detail?

**Comment by AislynLaurent** [comment]
This has been resolved! You should be able to make an account now.

**Comment by judithhouston** [comment]
Awesome, thanks a lot!

______________________________________
Judith Houston
Instrument Scientist - Small Angle Scattering

European Spallation Source ERIC
Box 176, SE-221 00 Lund, Sweden
Visiting address: Partikelgatan 2, 224 84 Lund

Mobile: +46 72 179 2021
E-mail:  ***@***.******@***.***>

www.ess.eu<http://www.ess.eu>

[signature_66574083]


From: Aislyn Laurent ***@***.***>
Reply-To: AislynLaurent/vesicle-viewer ***@***.***>
Date: Thursday, 24 June 2021 at 15:38
To: AislynLaurent/vesicle-viewer ***@***.***>
Cc: Judith Houston ***@***.***>, Author ***@***.***>
Subject: Re: [AislynLaurent/vesicle-viewer] registration error (#150)


This has been resolved! You should be able to make an account now.
