### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by juiceshih** [AislynLaurent/vesicle-viewer#153]
Hi,

Thank you so much for creating this very useful platform. I have encountered an error that bugs me. I was trying to create a custom lipid (d54-DMPC) and it works well by using the custom lipid at first place. However, while I am trying to modify the parameters by using edit function, I am not able to do so. Each time when I hit the "done" button, it give me the "Server Error (500)" error. I am wondering whether you can solve this? Thank you!!

Best regards,
Kuo-Chih

**Comment by AislynLaurent** [comment]
> 
> 
> Hi,
> 
> Thank you so much for creating this very useful platform. I have encountered an error that bugs me. I was trying to create a custom lipid (d54-DMPC) and it works well by using the custom lipid at first place. However, while I am trying to modify the parameters by using edit function, I am not able to do so. Each time when I hit the "done" button, it give me the "Server Error (500)" error. I am wondering whether you can solve this? Thank you!!
> 
> Best regards,
> Kuo-Chih

I'll have a look this week and try to diagnose the issue!

**Comment by AislynLaurent** [comment]
@juiceshih , this issue has been resolved! Thanks so much for your patience.
